import { BusinessType, ListingSummary, ListingType } from '@/types';

export const demoListings: ListingSummary[] = [
  {
    id: 'vip-palais',
    title: 'Le Palais VIP - Lounge & Nightclub',
    description: 'Le lieu le plus exclusif de Brazzaville pour vos soirees VIP.',
    listingType: ListingType.NIGHTCLUB_ENTRY,
    type: BusinessType.BAR_NIGHTCLUB,
    location: 'Brazzaville, Plateau',
    pricePerPerson: 15000,
    rating: 5.0,
    reviewCount: 128,
    images: [{ url: '/beach-club.png', altText: 'VIP Lounge' }],
    operator: { businessName: 'Le Palais Group', businessType: BusinessType.BAR_NIGHTCLUB, city: 'Brazzaville', region: 'Brazzaville' },
  },
  {
    id: 'kermesse-centrale',
    title: 'Grande Kermesse de la Republique',
    description: 'Loisirs, jeux, gastronomie locale et ambiance familiale unique.',
    listingType: ListingType.KERMESSE,
    type: BusinessType.TOURIST_SITE,
    location: 'Pointe-Noire, Cote Sauvage',
    pricePerPerson: 2000,
    rating: 4.8,
    reviewCount: 340,
    images: [{ url: '/gaming-demo.png', altText: 'Kermesse Activities' }],
    operator: { businessName: 'Mairie de PN', businessType: BusinessType.OTHER, city: 'Pointe-Noire', region: 'Kouilou' },
  },
  {
    id: 'mariage-prestige',
    title: 'Pack Mariage Royal - Salle Polyvalente',
    description: 'Organisation complete de votre mariage dans un cadre majestueux.',
    listingType: ListingType.EVENT_HALL_RENTAL,
    type: BusinessType.EVENT_HALL,
    location: 'Brazzaville, Kintele',
    priceFlatRate: 750000,
    rating: 4.9,
    reviewCount: 15,
    images: [{ url: '/events-demo.png', altText: 'Wedding Hall' }],
    operator: { businessName: 'Espace Prestige', businessType: BusinessType.EVENT_HALL, city: 'Brazzaville', region: 'Brazzaville' },
  },
  {
    id: 'gaming-elite',
    title: 'Gaming Lounge Elite - VR & PS5',
    description: 'La meilleure salle de jeux video high-tech du pays.',
    listingType: ListingType.LEISURE_ACTIVITY,
    type: BusinessType.OTHER,
    location: 'Pointe-Noire, Centre-Ville',
    pricePerPerson: 5000,
    rating: 4.7,
    reviewCount: 89,
    images: [{ url: '/gaming-demo.png', altText: 'Gaming Zone' }],
    operator: { businessName: 'Elite Gaming', businessType: BusinessType.OTHER, city: 'Pointe-Noire', region: 'Kouilou' },
  },
  {
    id: 'bar-ocean',
    title: 'L\'Ocean Bleu - Bar & VIP',
    description: 'Cocktails exotiques et vue imprenable sur l\'Atlantique.',
    listingType: ListingType.NIGHTCLUB_ENTRY,
    type: BusinessType.BAR_NIGHTCLUB,
    location: 'Pointe-Noire, Plage',
    pricePerPerson: 10000,
    rating: 4.6,
    reviewCount: 56,
    images: [{ url: '/restaurant-demo.png', altText: 'Ocean Bar' }],
    operator: { businessName: 'Groupe Horizon', businessType: BusinessType.BAR_NIGHTCLUB, city: 'Pointe-Noire', region: 'Kouilou' },
  },
  // On ajoute des entrées pour arriver à 25 ou proche pour la démo
  {
    id: 'demo-odzala',
    title: 'Parc National Odzala-Kokoua',
    description: 'Immersion nature dans le Nord Congo.',
    listingType: ListingType.EXCURSION,
    type: BusinessType.TOURIST_SITE,
    location: 'Cuvette-Ouest',
    pricePerPerson: 85000,
    rating: 4.9,
    reviewCount: 42,
    images: [{ url: '/mayombe_luxury_resort.png', altText: 'Odzala' }],
    operator: { businessName: 'Odzala Exp', businessType: BusinessType.TOURIST_SITE, city: 'Odzala', region: 'Cuvette-Ouest' },
  },
  {
    id: 'hotel-atlantic',
    title: 'Atlantic Lodge - Suite Royale',
    description: 'Le luxe absolu au bord de l\'ocean.',
    listingType: ListingType.HOTEL_SUITE,
    type: BusinessType.HOTEL,
    location: 'Pointe-Noire',
    pricePerNight: 120000,
    rating: 5.0,
    reviewCount: 78,
    images: [{ url: '/hotel-demo.png', altText: 'Atlantic' }],
    operator: { businessName: 'Atlantic Group', businessType: BusinessType.HOTEL, city: 'Pointe-Noire', region: 'Kouilou' },
  }
];

// Generation dynamique pour arriver a 25 pour la demo visuelle
for (let i = 8; i <= 25; i++) {
  demoListings.push({
    id: `demo-op-${i}`,
    title: `Etablissement Partenaire #${i}`,
    description: 'Un service de qualite selectionne pour vous par Congo Tourisme.',
    listingType: i % 2 === 0 ? ListingType.RESTAURANT_TABLE : ListingType.KERMESSE,
    type: i % 2 === 0 ? BusinessType.RESTAURANT : BusinessType.TOURIST_SITE,
    location: i % 3 === 0 ? 'Brazzaville' : 'Pointe-Noire',
    pricePerPerson: 10000 + (i * 500),
    rating: 4.0 + (Math.random()),
    reviewCount: 10 + i,
    images: [{ url: '/welcome.png', altText: 'Congo' }],
    operator: { businessName: `Operateur ${i}`, businessType: BusinessType.OTHER, city: 'Congo', region: 'Congo' },
  });
}
